on: [push]
jobs:
  mac:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --features=sudo,output
      - run: cargo doc --features=sudo,output
  win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - run: cargo test --features=sudo,output
      - run: cargo doc --features=sudo,output